#!/bin/env php
<?php

require_once __DIR__ . '/../bootstrap/client.php';

$usage = 'usage: ' . PHP_EOL .
    '    ' . basename(__FILE__) . ' <host> <repository name> <number>' . PHP_EOL;

execute(function () use ($authorization, $baseUrl, $command, $values) {

    throwExceptionIfInvalidNumberOfValuesWasProvided($values, 3);

    list($host, $repositoryName, $number) = extractValues($values);

    throwExceptionIfValueIsInvalid($host, 'host');
    throwExceptionIfValueIsInvalid($repositoryName, 'repository name');
    throwExceptionIfValueIsInvalid($number, 'number');

    $url    = $baseUrl . '/' . $repositoryName . '/' . $number;
    $lines  = $command->delete($host, $url);

    foreach ($lines as $line) {
        echo $line . PHP_EOL;
    }
}, $usage);
