#!/usr/bin/env php
<?php

require_once __DIR__ . '/../bootstrap/client.php';

$usage = 'usage: ' . PHP_EOL .
    '    ' . basename(__FILE__) . ' <host> <repository name>' . PHP_EOL;

execute(function () use ($baseUrl, $command, $values) {

    throwExceptionIfInvalidNumberOfValuesWasProvided($values, 2);

    list($host, $repositoryName) = extractValues($values);

    throwExceptionIfValueIsInvalid($host, 'host');
    throwExceptionIfValueIsInvalid($repositoryName, 'repository name');

    $url    = $baseUrl . '/' . $repositoryName;
    $lines  = $command->delete($host, $url);

    foreach ($lines as $line) {
        echo $line . PHP_EOL;
    }
}, $usage);
